definitions:
  auth.EmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      token:
        type: string
      uid:
        type: string
    type: object
  auth.PasswordResetRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.ProfileStatusResponse:
    properties:
      perfil_completado:
        type: boolean
    type: object
  auth.ProfileUpdateRequest:
    properties:
      ano_ingreso:
        type: string
      fecha_nacimiento:
        type: string
      id_carrera:
        type: integer
    type: object
  auth.RegisterRequest:
    properties:
      apellidos:
        type: string
      email:
        type: string
      nombres:
        type: string
      password:
        type: string
    required:
    - apellidos
    - email
    - nombres
    - password
    type: object
  auth.RegisterRequest_admin:
    properties:
      Email_admin:
        type: string
      Nombre_admin:
        type: string
      password:
        type: string
    required:
    - Email_admin
    - Nombre_admin
    - password
    type: object
  auth.RegisterRequest_empresa:
    properties:
      Email_empresa:
        type: string
      Nombre_empresa:
        type: string
      password:
        type: string
    required:
    - Email_empresa
    - Nombre_empresa
    - password
    type: object
  auth.RegisterResponse:
    properties:
      firebase_uid:
        type: string
      message:
        type: string
    type: object
  auth.RegisterResponse_admin:
    properties:
      firebase_uid:
        type: string
      message:
        type: string
    type: object
  auth.RegisterResponse_empresa:
    properties:
      firebase_uid:
        type: string
      message:
        type: string
    type: object
  auth.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  database.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /check-postulaciones:
    get:
      description: Verifica cambios en la tabla de postulaciones y envía correos electrónicos
        si hay cambios
      produces:
      - application/json
      responses:
        "200":
          description: Verificación completada
          schema:
            type: string
        "500":
          description: Error al verificar cambios
          schema:
            $ref: '#/definitions/database.ErrorResponse'
      summary: Verificar cambios en la tabla de postulaciones
      tags:
      - postulaciones
  /complete-profile:
    post:
      consumes:
      - application/json
      description: Permite a los usuarios autenticados completar o actualizar su perfil,
        incluida la foto de perfil
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Datos para actualizar el perfil
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/auth.ProfileUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Perfil actualizado correctamente
          schema:
            $ref: '#/definitions/auth.SuccessResponse'
        "400":
          description: Datos inválidos
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "401":
          description: Usuario no autenticado
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Error al actualizar el perfil
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Completar o actualizar perfil de usuario
      tags:
      - profile
  /login:
    post:
      consumes:
      - application/json
      description: Autentica al usuario utilizando Firebase y devuelve un token
      parameters:
      - description: Datos de inicio de sesión
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Inicio de sesión exitoso
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Datos inválidos
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "401":
          description: Credenciales incorrectas
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Inicia sesión un usuario
      tags:
      - auth
  /password-reset:
    post:
      consumes:
      - application/json
      description: Permite a los usuarios recuperar su contraseña mediante un correo
        de recuperación
      parameters:
      - description: Correo del usuario
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/auth.PasswordResetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Correo de recuperación enviado con éxito
          schema:
            $ref: '#/definitions/auth.SuccessResponse'
        "400":
          description: Email requerido
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Error al enviar el correo de recuperación
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Envía un correo de recuperación de contraseña
      tags:
      - password
  /profile-status:
    get:
      description: Retorna si el perfil ha sido completado o no
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Estado del perfil
          schema:
            $ref: '#/definitions/auth.ProfileStatusResponse'
        "400":
          description: Datos inválidos
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "401":
          description: Usuario no autenticado
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Obtener estado del perfil
      tags:
      - profile
  /register:
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario en Firebase y lo guarda en la base de datos
        local
      parameters:
      - description: Datos del usuario a registrar
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Usuario registrado correctamente
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "400":
          description: Solicitud inválida
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: Registra un nuevo usuario
      tags:
      - auth
  /register_admin:
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario en Firebase y lo guarda en la base de datos
        local
      parameters:
      - description: Datos del usuario a registrar
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest_admin'
      produces:
      - application/json
      responses:
        "200":
          description: Usuario registrado correctamente
          schema:
            $ref: '#/definitions/auth.RegisterResponse_admin'
        "400":
          description: Solicitud inválida
          schema:
            $ref: '#/definitions/auth.RegisterResponse_admin'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/auth.RegisterResponse_admin'
      summary: Registra un nuevo usuario
      tags:
      - auth
  /register_empresa:
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario en Firebase y lo guarda en la base de datos
        local
      parameters:
      - description: Datos del usuario a registrar
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest_empresa'
      produces:
      - application/json
      responses:
        "200":
          description: Usuario registrado correctamente
          schema:
            $ref: '#/definitions/auth.RegisterResponse_empresa'
        "400":
          description: Solicitud inválida
          schema:
            $ref: '#/definitions/auth.RegisterResponse_empresa'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/auth.RegisterResponse_empresa'
      summary: Registra un nuevo usuario
      tags:
      - auth
  /resend-verification:
    post:
      consumes:
      - application/json
      description: Reenvía el correo de verificación a un usuario registrado
      parameters:
      - description: Correo del usuario
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/auth.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Correo de verificación enviado nuevamente
          schema:
            $ref: '#/definitions/auth.SuccessResponse'
        "400":
          description: Email requerido
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "404":
          description: Usuario no encontrado
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Reenviar correo de verificación
      tags:
      - verification
  /sendemail:
    post:
      consumes:
      - application/json
      description: Sends an email to the user with the updated status of their application
      parameters:
      - description: Recipient email address
        in: query
        name: to
        required: true
        type: string
      - description: Application status
        in: query
        name: estadoPostulacion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Send an email notification
      tags:
      - email
  /upload-image:
    post:
      consumes:
      - multipart/form-data
      description: Sube una imagen a Firebase Storage y actualiza el campo de foto
        de perfil del usuario autenticado
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Imagen a subir
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: URL de la imagen subida y mensaje de éxito
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Error en la solicitud
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Usuario no autenticado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error al subir la imagen
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Subir una imagen de perfil
      tags:
      - upload
swagger: "2.0"
